# Generated by Django 2.1.4 on 2018-12-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledimage',
            name='image',
            field=models.ImageField(upload_to='static/uploaded_images/'),
        ),
    ]
