# Generated by Django 2.1.4 on 2019-01-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0002_auto_20181229_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to='static/uploaded_images/', width_field='width'),
        ),
    ]
