# Generated by Django 2.1.4 on 2019-01-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_annotation', '0005_auto_20190113_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeledimage',
            name='image',
            field=models.ImageField(upload_to='static/uploaded_images/'),
        ),
    ]
